version: '3.8'

services:
    household-php:
        container_name: household-php
        build:
            context: ./php
            args:
                - PUID=${PUID}
                - PGID=${PGID}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        volumes:
            - ./../:/var/www/household
        networks:
            family:
                aliases:
                    - household-php
        restart: always
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    household-db:
        container_name: household-db
        image: postgres:15.4-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - auth_db_data:/var/lib/postgresql/data:rw
        networks:
            family:
                aliases:
                    - household-db
        restart: always

networks:
    family:
        external: true

volumes:
    auth_db_data: